name: Build mo files

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install gettext
      run: sudo apt install gettext
    - name: Build
      run: |
        for i in `find . -name '*.po'`; do echo `basename $i` && msgfmt -o `basename $i .po`.mo `basename $i`; done;
        mkdir langs
        cp *.mo langs/
        cd langs && zip -q -r langs.zip * && mv langs.zip ../ && cd -
    - name: Upload a Langs Artifact
      uses: actions/upload-artifact@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: https://uploads.github.com/repos/typecho/languages/releases/58851283/assets{?name,label}
        release_id: 58851283
        asset_path: ./langs.zip
        asset_name: langs.zip
        asset_content_type: application/zip
        max_releases: 1
